server/email_website/email_website/urls.py
from django.contrib import admin
from django.urls import path, include

import subscriptions
from website.views import home, signup

urlpatterns = [
	path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('subscription/', include('subscriptions.urls')),
    path('form/<str:api_key>/', subscriptions.views.form, name='form'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', signup, name='signup')
       
]

server/email_website/subscriptions/urls.py
from django.urls import path

from . import views

app_name = 'subscriptions'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:subscription_id>/', views.detail, name='detail'),
    # path('form/<str:api_key>/', views.form, name='form'),
]

server/email_website/subscriptions/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Subscription(models.Model):
    pub_date = models.DateTimeField('date created', default=datetime.now, blank=True)
    api_key = models.CharField(max_length=50)
    email =  models.CharField(max_length=200)

    def __str__(self):
        return f'Subscription from {self.email}'

class FormData(models.Model):
    subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE)
    form_data = models.CharField(max_length=2000, default=datetime.now, blank=True)
    send_date = models.DateTimeField('date sent')

    def __str__(self):
        return f'FormData from {self.form_data}'

server/email_website/website/models.py
from django.db import models

# Create your models here.

server/email_website/subscriptions/views.py
from django.http import HttpResponse, Http404

from django.template import loader

from .models import Subscription, FormData

from django.shortcuts import get_object_or_404, render

from datetime import datetime

def index(request):
    latest_subscription_list = Subscription.objects.order_by('-pub_date')[:5]
    template = loader.get_template('subscriptions/index.html')
    context = {
        'latest_subscription_list': latest_subscription_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, subscription_id):
	subscription = get_object_or_404(Subscription, pk=subscription_id)
	return render(request, 'subscriptions/detail.html', {'subscription': subscription})

import smtplib, ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
def send_email(receiver_email, msg):
	port = 465  # For starttls
	smtp_server = "smtp.gmail.com"
	sender_email = "email.website.form@gmail.com"
	password = 'qecmid-pagwan-jodmA4'
	context = ssl.create_default_context()

	message = MIMEMultipart("alternative")
	message["Subject"] = "Form comleted"
	message["From"] = sender_email
	message["To"] = receiver_email

	# Create the plain-text and HTML version of your message
	text = """\
	Hi,
	How are you?"""

	html = """\
	<html>
	  <body>
	    <p>Hi,<br>
	       {}
	    </p>
	  </body>
	</html>
	""".format(msg)
	print(html)

	# Turn these into plain/html MIMEText objects
	part1 = MIMEText(text, "plain")
	part2 = MIMEText(html, "html")

	# Add HTML/plain-text parts to MIMEMultipart message
	# The email client will try to render the last part first
	message.attach(part1)
	message.attach(part2)

	with smtplib.SMTP_SSL("smtp.gmail.com", port, context=context) as server:
		server.login(sender_email, password)
		server.sendmail(sender_email, receiver_email, message.as_string())
	pass

def form(request, api_key):
	try:
		subscription = Subscription.objects.get(api_key=api_key)
	except:
		return HttpResponse('YOUR_API_KEY is not recognised. Please get a key on your profile page at https://email-website.com and use it.')
	if request.method == 'POST':
		post_data = request.POST.dict()
		post_data.pop("csrfmiddlewaretoken", None)
		form_data = FormData(subscription = subscription, form_data = str(post_data), send_date=datetime.now())
		form_data.save()
		send_email(receiver_email=subscription.email, msg=str(post_data))
	else:
		post_data = None
	return render(request, 'subscriptions/form.html', {
		'subscription': subscription,
		'post_data': post_data,
        'api_key': api_key
    })

server/email_website/website/views.py
from django.http import HttpResponse, Http404

from django.template import loader

from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404, render, redirect

from django.contrib.auth import login, authenticate

import uuid

from subscriptions.models import Subscription

# At this point, user is a User object that has already been saved
# to the database. You can continue to change its attributes
# if you want to change other fields.
from datetime import datetime


def home(request):
	try:
		subscription = Subscription.objects.get(email=request.user.username)
		api_key = subscription.api_key
		print (api_key)
	except Exception as e:
		print (e)
		api_key = None
	template = loader.get_template('website/index.html')
	context = {
		'api_key' : api_key
	}
	return HttpResponse(template.render(context, request))

def create_subscription(user):
	subscription = Subscription(pub_date = datetime.now(), api_key = uuid.uuid4(), email = user.username)
	subscription.save()


def signup(request):
	template = loader.get_template('website/signup.html')
	context = {}
	error_msg = None

	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			create_subscription(user)
			return redirect('home')
		else:
			error_msg = form.errors
			form = UserCreationForm()
			

	else:
		form = UserCreationForm()
	return render(request, 'website/signup.html', {'form': form, 'error_msg': error_msg}) 

server/email_website/subscriptions/templates/subscriptions/detail.html
<h1>{{ subscription.email }}</h1>
<p>{{ subscription.pub_date }}</p>
<p>{{ subscription.api_key }}</p>
<ul>
{% for formdata in subscription.formdata_set.all %}
    <li>{{ formdata.send_date }}</li>
{% endfor %}
</ul>

server/email_website/subscriptions/templates/subscriptions/form.html
<form action="{% url 'form' api_key %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>Test your form submission here </h1></legend>
    
    <p>Make sure your form has the <code>method="post"</code> attribute.</p>
    <p>Your link to POST forms is: https://email-website.com/form/{{ api_key }}</p>
    <p>Form data will be sent to: {{ subscription.email }}</p>
    {% if post_data %}<p><strong>{{ post_data }}</strong></p>{% endif %}
        <label for="email">Your Email</label>
		<input name="Email" id="email" type="email">
		<label for="message">Your Message</label>
		<textarea name="Message" id="message"> </textarea>
		<button type="submit">Submit</button>
</fieldset>
</form>

server/email_website/subscriptions/templates/subscriptions/index.html
{% if latest_subscription_list %}
    <ul>
    {% for subscription in latest_subscription_list %}
        <li><a href="{% url 'subscriptions:detail' subscription.id %}">{{ subscription.email }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

server/email_website/website/templates/website/index.html
<!DOCTYPE html>
<html lang = "en">
<head>
	<meta http-equiv = "content-language" content = "en">
	<meta name="msvalidate.01" content="F679B924D64A480A1A28113B9E600EE5" />
	<meta name="description" content="Send emails from website without PHP or backend, you can send form from HTML for free or use special premium options ">
	<title>Send email from static website</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js?autoload=true&amp;skin=sunburst&amp;lang=css" defer=""></script>
	<!-- Yandex.Metrika counter -->
	<script type="text/javascript" >
	   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
	   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
	   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

	   ym(81046150, "init", {
	        clickmap:true,
	        trackLinks:true,
	        accurateTrackBounce:true,
	        webvisor:true
	   });
	</script>
	<noscript><div><img src="https://mc.yandex.ru/watch/81046150" style="position:absolute; left:-9999px;" alt="metrika" /></div></noscript>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Z9V1PHS8PV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Z9V1PHS8PV');
</script>
	<!-- /Yandex.Metrika counter -->
</head>
<body>
	<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-3 pt-1">
        <a class="d-flex align-items-center text-dark text-decoration-none" href="#"><span class="fs-4">Email website</span></a>
      </div>
      <div class="col-3 text-center">
      </div>
      <div class="col-3 d-flex justify-content-end align-items-center">
        {% if user.is_authenticated %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'logout' %}" >Logout        </a>
        {% else %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'signup' %}" style="margin-right: 5px">Sign up</a>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'login' %}" >Sign in        </a>
        {% endif %}
      </div>
    </div>
  </header>

  <main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-8 col-md-8 mx-auto">
        <h1 class="fw-light">Simply send email from a static HTML website</h1>
        <p class="lead text-muted"> No PHP or special backend required. Sign in, get a secret key and receive HTML form submissons from your website to your email. <br>Copy the following code to your website and style it appropriately.</p>
        
        <pre style="text-align: left" class="prettyprint" id="quine">
{% if api_key%}
&ltform action="https://email-website.com/form/{{ api_key}}" method="post"&gt
  &ltlabel for="email"&gtYour Email&lt/label&gt
  &ltinput name="Email" id="email" type="email"&gt
  &ltlabel for="message"&gtYour Message&lt/label&gt
  &lttextarea name="Message" id="message"&gt &lt/textarea&gt
  &ltbutton type="submit"&gtSubmit&lt/button&gt
&lt/form>
{% else %}
&ltform action="https://email-website.com/form/YOUR_API_KEY" method="post"&gt
  &ltlabel for="email"&gtYour Email&lt/label&gt
  &ltinput name="Email" id="email" type="email"&gt
  &ltlabel for="message"&gtYour Message&lt/label&gt
  &lttextarea name="Message" id="message"&gt &lt/textarea&gt
  &ltbutton type="submit"&gtSubmit&lt/button&gt
&lt/form>
{% endif %}
        </pre>

        <p>
          {% if user.is_authenticated %}
            <p><code class="small"> Your API key is: {{ api_key }} </code> </p>
              <p><code class="small"> Emails will be sent to: {{ user.username }} </code> </p>
          {% else %}
            <a href="{% url 'signup' %}" class="btn btn-primary my-2">Get API key</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>

</main>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">&copy; 2017 - 2021</small>
      </div>
    </div>
  </footer>
</div>

</body>
</html>

server/email_website/website/templates/website/signup.html
<!-- templates/registration/login.html -->
<html lang = "en">
<head>
	<meta http-equiv = "content-language" content = "en">
	<meta name="msvalidate.01" content="F679B924D64A480A1A28113B9E600EE5" />
	<meta name="description" content="Send emails from website without PHP or backend, you can send form from HTML for free or use special premium options ">
	<title>Send email from static website</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js?autoload=true&amp;skin=sunburst&amp;lang=css" defer=""></script>
	<!-- Yandex.Metrika counter -->
	<script type="text/javascript" >
	   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
	   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
	   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

	   ym(81046150, "init", {
	        clickmap:true,
	        trackLinks:true,
	        accurateTrackBounce:true,
	        webvisor:true
	   });
	</script>
	<noscript><div><img src="https://mc.yandex.ru/watch/81046150" style="position:absolute; left:-9999px;" alt="metrika" /></div></noscript>
	<!-- /Yandex.Metrika counter -->
</head>
  <body class="text-center">
  	<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-3 pt-1">
        <a class="d-flex align-items-center text-dark text-decoration-none" href="/"><span class="fs-4">Email website</span></a>
      </div>
      <div class="col-3 text-center">
      </div>
      <div class="col-3 d-flex justify-content-end align-items-center">
      </div>
    </div>
  </header>
    
<main class="form-signin" style="width: 100%; max-width: 330px; padding: 15px; margin: auto;">

	<form method="post">
		<h1 class="h3 mb-3 fw-normal">Please sign up</h1>
		{% csrf_token %}
		{% if error_msg %}
		{{error_msg}} 
		{% endif %}
		<div class="form-floating" >
			<input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username" style="margin-bottom: -1px; border-bottom-right-radius: 0; border-bottom-left-radius: 0;" class="form-control">
			<label for="id_username">Email:</label>
		</div>
		<div class="form-floating" >
			<input type="password" name="password1" autocomplete="new-password" required="" id="id_password1" class="form-control" style="margin-bottom: -1px; border-bottom-right-radius: 0; border-bottom-left-radius: 0; border-top-left-radius: 0;border-top-right-radius: 0;">
			<label for="id_password1">Password:</label>

		</div>
		<div class="form-floating" >
			<input type="password" name="password2" autocomplete="new-password" required="" id="id_password2" style="margin-bottom: 10px; border-top-left-radius: 0;border-top-right-radius: 0;" class="form-control"> 
			<label for="id_password2">Password confirmation:</label>

		</div>
		<button type="submit" class="w-100 btn btn-lg btn-primary">Sign up</button>
	</form>

</main>
</div>
  

</body></html>